model:
  system: postgres
  driver: pgx
  address: localhost
  port: "5432"
  username: postgres
  password: '09102000'
  database: plan_active_db
  sslmode: disable
controller/go:
  port: :8085
  data: /data/
view:
  system: npm
  command to build: run build
  src: src
  index: index.html
  destination: build
