model :
  system : postgres
  driver : pgx
  address : localhost
  port : 5432
  username : postgres
  password : 09102000

controller/go :
  version : 1.14
  port : 8085

view:
  system : node.js
  command to build : npm run build
  src : ./src


